package com.nazar.chumbey.libraryofophthalmologicexaminationsofpatients.services.servicesImpl;

import com.nazar.chumbey.libraryofophthalmologicexaminationsofpatients.services.OphthalmicStatusService;

public class OphthalmicStatusServiceImpl implements OphthalmicStatusService {
}
